### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by arturoaviles** [kamranahmedse/tab-switcher#10]
I made this steps:

1. Installed the chrome extension in Chrome 53.0.2785.116 in Windows 8.1 Enterprise
2. Closed Chrome
3. Opened it
4. Opened some tabs and browsed the internet
5. Clicked Ctrl + Shift + K and Enter but nothing happened
 
Is this extension for Windows and/or just MacOS and Linux?

Thanks

**Comment by kamranahmedse** [comment]
Hey @arturoaviles,

I tested it earlier on windows 7 and 8 and yes it does work on it. Could you please 

- Check the console if you are getting any errors? 
- What was the website that you tried it on? It won't work on the new tab and chrome webstore, it doesn't work on those pages.

**Comment by arturoaviles** [comment]
Hey @kamranahmedse,

- I'm trying to figure out how to check your extension with the console. 

![capture](https://cloud.githubusercontent.com/assets/2120957/18859483/7b12616c-8442-11e6-947d-392d3a09fb33.PNG)

- I tried on websites like... google.com, github.com, facebook.com, stackoverflow, etc...
- I'm not using the metro application.

**Comment by simonflk** [comment]
I had the same issue (Chrome 53, Linux)
My issue was caused by a conflict with another extension which was set up to use Ctrl+Shift+K (PushBullet)
I resolved the issue, by unbinding Ctrl+Shift+K with the conflicting extension, and re-installing Tab Switcher. For me, simply binding Ctrl+Shift+K to Tab Switcher did not in itself fix it - Only the reinstall did.

To edit keyboard shortcuts:
> Just head to chrome://extensions/ in your browser's address bar to open up the extensions page. Scroll down to the bottom and you'll see a Keyboard Shortcuts option. Click it, and you can set up custom shortcuts for some of you extensions.

--- http://lifehacker.com/add-custom-keyboard-shortcuts-to-chrome-extensions-for-1595322121

**Comment by arturoaviles** [comment]
It worked. Pushbullet shortcut was the problem as you said.
Thanks @simonflk!
